<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('countries')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');


        $rows = [];
        $rows[] = ['country_code' => 'AF','country_name' => 'Afghanistan', 'phone_code'=>'93'];
        $rows[] = ['country_code' => 'AX','country_name' => 'Aland Islands', 'phone_code'=>'+358-18'];
        $rows[] = ['country_code' => 'AL','country_name' => 'Albania', 'phone_code'=>'355'];
        $rows[] = ['country_code' => 'DZ','country_name' => 'Algeria', 'phone_code'=>'213'];
        $rows[] = ['country_code' => 'DS','country_name' => 'American Samoa', 'phone_code'=>'+1-684'];
        $rows[] = ['country_code' => 'AD','country_name' => 'Andorra', 'phone_code'=>'376'];
        $rows[] = ['country_code' => 'AO','country_name' => 'Angola', 'phone_code'=>'244'];
        $rows[] = ['country_code' => 'AI','country_name' => 'Anguilla', 'phone_code'=>'+1-264'];
        $rows[] = ['country_code' => 'AQ','country_name' => 'Antarctica', 'phone_code'=>'0'];
        $rows[] = ['country_code' => 'AG','country_name' => 'Antigua and Barbuda', 'phone_code'=>'+1-268'];
        $rows[] = ['country_code' => 'AR','country_name' => 'Argentina', 'phone_code'=>'54'];
        $rows[] = ['country_code' => 'AM','country_name' => 'Armenia', 'phone_code'=>'374'];
        $rows[] = ['country_code' => 'AW','country_name' => 'Aruba', 'phone_code'=>'297'];
        $rows[] = ['country_code' => 'AU','country_name' => 'Australia', 'phone_code'=>'61'];
        $rows[] = ['country_code' => 'AT','country_name' => 'Austria', 'phone_code'=>'43'];
        $rows[] = ['country_code' => 'AZ','country_name' => 'Azerbaijan', 'phone_code'=>'994'];
        $rows[] = ['country_code' => 'BS','country_name' => 'Bahamas', 'phone_code'=>'+1-242'];
        $rows[] = ['country_code' => 'BH','country_name' => 'Bahrain', 'phone_code'=>'973'];
        $rows[] = ['country_code' => 'BD','country_name' => 'Bangladesh', 'phone_code'=>'880'];
        $rows[] = ['country_code' => 'BB','country_name' => 'Barbados', 'phone_code'=>'+1-246'];
        $rows[] = ['country_code' => 'BY','country_name' => 'Belarus', 'phone_code'=>'375'];

        $rows[] = ['country_code' => 'BE','country_name' => 'Belgium', 'phone_code'=>'32'];
        $rows[] = ['country_code' => 'BZ','country_name' => 'Belize', 'phone_code'=>'501'];
        $rows[] = ['country_code' => 'BJ','country_name' => 'Benin', 'phone_code'=>'229'];
        $rows[] = ['country_code' => 'BM','country_name' => 'Bermuda', 'phone_code'=>'+1-441'];
        $rows[] = ['country_code' => 'BT','country_name' => 'Bhutan', 'phone_code'=>'975'];
        $rows[] = ['country_code' => 'BO','country_name' => 'Bolivia', 'phone_code'=>'591'];
        $rows[] = ['country_code' => 'BA','country_name' => 'Bosnia and Herzegovina', 'phone_code'=>'387'];
        $rows[] = ['country_code' => 'BW','country_name' => 'Botswana', 'phone_code'=>'267'];
        $rows[] = ['country_code' => 'BV','country_name' => 'Bouvet Island', 'phone_code'=>'0'];
        $rows[] = ['country_code' => 'BR','country_name' => 'Brazil', 'phone_code'=>'55'];
        $rows[] = ['country_code' => 'IO','country_name' => 'British Indian Ocean Territory', 'phone_code'=>'246'];
        $rows[] = ['country_code' => 'BN','country_name' => 'Brunei Darussalam', 'phone_code'=>'673'];
        $rows[] = ['country_code' => 'BG','country_name' => 'Bulgaria', 'phone_code'=>'359'];
        $rows[] = ['country_code' => 'BF','country_name' => 'Burkina Faso', 'phone_code'=>'226'];
        $rows[] = ['country_code' => 'BI','country_name' => 'Burundi', 'phone_code'=>'257'];
        $rows[] = ['country_code' => 'KH','country_name' => 'Cambodia', 'phone_code'=>'855'];
        $rows[] = ['country_code' => 'CM','country_name' => 'Cameroon', 'phone_code'=>'237'];
        $rows[] = ['country_code' => 'CA','country_name' => 'Canada', 'phone_code'=>'1'];
        $rows[] = ['country_code' => 'CV','country_name' => 'Cape Verde', 'phone_code'=>'238'];
        $rows[] = ['country_code' => 'KY','country_name' => 'Cayman Islands', 'phone_code'=>'+1-345'];
        $rows[] = ['country_code' => 'CF','country_name' => 'Central African Republic', 'phone_code'=>'236'];
        $rows[] = ['country_code' => 'TD','country_name' => 'Chad', 'phone_code'=>'235'];
        $rows[] = ['country_code' => 'CL','country_name' => 'Chile', 'phone_code'=>'56'];
        $rows[] = ['country_code' => 'CN','country_name' => 'China', 'phone_code'=>'86'];
        $rows[] = ['country_code' => 'CX','country_name' => 'Christmas Island', 'phone_code'=>'61'];
        $rows[] = ['country_code' => 'CC','country_name' => 'Cocos (Keeling) Islands', 'phone_code'=>'61'];
        $rows[] = ['country_code' => 'CO','country_name' => 'Colombia', 'phone_code'=>'57'];
        $rows[] = ['country_code' => 'KM','country_name' => 'Comoros', 'phone_code'=>'269'];
        $rows[] = ['country_code' => 'CG','country_name' => 'Republic of the Congo', 'phone_code'=>'242'];
        $rows[] = ['country_code' => 'CG','country_name' => 'Democratic Republic of the Congo', 'phone_code'=>'243'];
        $rows[] = ['country_code' => 'CK','country_name' => 'Cook Islands', 'phone_code'=>'682'];
        $rows[] = ['country_code' => 'CR','country_name' => 'Costa Rica', 'phone_code'=>'506'];
        $rows[] = ['country_code' => 'HR','country_name' => 'Croatia', 'phone_code'=>'385'];
        $rows[] = ['country_code' => 'CU','country_name' => 'Cuba', 'phone_code'=>'53'];
        $rows[] = ['country_code' => 'CY','country_name' => 'Cyprus', 'phone_code'=>'357'];
        $rows[] = ['country_code' => 'CZ','country_name' => 'Czech Republic', 'phone_code'=>'420'];
        $rows[] = ['country_code' => 'DK','country_name' => 'Denmark', 'phone_code'=>'45'];
        $rows[] = ['country_code' => 'DJ','country_name' => 'Djibouti', 'phone_code'=>'253'];
        $rows[] = ['country_code' => 'DM','country_name' => 'Dominica', 'phone_code'=>'+1-767'];
        $rows[] = ['country_code' => 'DO','country_name' => 'Dominica Republic', 'phone_code'=>'+1-809 and 1-829'];
        $rows[] = ['country_code' => 'TP','country_name' => 'East Timor', 'phone_code'=>'670'];
        $rows[] = ['country_code' => 'EC','country_name' => 'Ecuador', 'phone_code'=>'593'];
        $rows[] = ['country_code' => 'EG','country_name' => 'Egypt', 'phone_code'=>'20'];
        $rows[] = ['country_code' => 'SV','country_name' => 'El Salvador', 'phone_code'=>'503'];
        $rows[] = ['country_code' => 'GQ','country_name' => 'Equatorial Guinea', 'phone_code'=>'240'];
        $rows[] = ['country_code' => 'ER','country_name' => 'Eritrea', 'phone_code'=>'291'];
        $rows[] = ['country_code' => 'EE','country_name' => 'Estonia', 'phone_code'=>'372'];
        $rows[] = ['country_code' => 'ET','country_name' => 'Ethiopia', 'phone_code'=>'251'];
        $rows[] = ['country_code' => 'FK','country_name' => 'Falkland Islands (Malvinas)', 'phone_code'=>'500'];
        $rows[] = ['country_code' => 'FO','country_name' => 'Faroe Islands', 'phone_code'=>'298'];
        $rows[] = ['country_code' => 'FJ','country_name' => 'Fiji', 'phone_code'=>'679'];
        $rows[] = ['country_code' => 'FI','country_name' => 'Finland', 'phone_code'=>'358'];
        $rows[] = ['country_code' => 'FR','country_name' => 'France', 'phone_code'=>'33'];
        $rows[] = ['country_code' => 'FX','country_name' => 'France, Metropolitan', 'phone_code'=>''];
        $rows[] = ['country_code' => 'GF','country_name' => 'French Guiana', 'phone_code'=>'594'];
        $rows[] = ['country_code' => 'PF','country_name' => 'French Polynesia', 'phone_code'=>'689'];
        $rows[] = ['country_code' => 'TF','country_name' => 'French Southern Territories', 'phone_code'=>''];
        $rows[] = ['country_code' => 'GA','country_name' => 'Gabon', 'phone_code'=>'241'];
        $rows[] = ['country_code' => 'GM','country_name' => 'Gambia', 'phone_code'=>'220'];
        $rows[] = ['country_code' => 'GE','country_name' => 'Georgia', 'phone_code'=>'995'];
        $rows[] = ['country_code' => 'DE','country_name' => 'Germany', 'phone_code'=>'49'];
        $rows[] = ['country_code' => 'GH','country_name' => 'Ghana', 'phone_code'=>'233'];
        $rows[] = ['country_code' => 'GI','country_name' => 'Gibraltar', 'phone_code'=>'350'];
        $rows[] = ['country_code' => 'GK','country_name' => 'Guernsey', 'phone_code'=>'+44-1481'];
        $rows[] = ['country_code' => 'GR','country_name' => 'Greece', 'phone_code'=>'30'];
        $rows[] = ['country_code' => 'GL','country_name' => 'Greenland', 'phone_code'=>'299'];
        $rows[] = ['country_code' => 'GD','country_name' => 'Grenada', 'phone_code'=>'+1-473'];
        $rows[] = ['country_code' => 'GP','country_name' => 'Guadeloupe', 'phone_code'=>'590'];
        $rows[] = ['country_code' => 'GU','country_name' => 'Guam', 'phone_code'=>'+1-671'];
        $rows[] = ['country_code' => 'GT','country_name' => 'Guatemala', 'phone_code'=>'502'];
        $rows[] = ['country_code' => 'GN','country_name' => 'Guinea', 'phone_code'=>'224'];
        $rows[] = ['country_code' => 'GW','country_name' => 'Guinea-Bissau', 'phone_code'=>'245'];
        $rows[] = ['country_code' => 'GY','country_name' => 'Guyana', 'phone_code'=>'592'];
        $rows[] = ['country_code' => 'HT','country_name' => 'Haiti', 'phone_code'=>'509'];
        $rows[] = ['country_code' => 'HM','country_name' => 'Heard Island and McDonald Islands', 'phone_code'=>''];
        $rows[] = ['country_code' => 'HN','country_name' => 'Honduras', 'phone_code'=>'504'];
        $rows[] = ['country_code' => 'HK','country_name' => 'Hong Kong', 'phone_code'=>'852'];
        $rows[] = ['country_code' => 'HU','country_name' => 'Hungary', 'phone_code'=>'36'];
        $rows[] = ['country_code' => 'IS','country_name' => 'Iceland', 'phone_code'=>'354'];
        $rows[] = ['country_code' => 'IN','country_name' => 'India', 'phone_code'=>'91'];
        $rows[] = ['country_code' => 'IM','country_name' => 'Isle of Man', 'phone_code'=>'+44-1624'];
        $rows[] = ['country_code' => 'ID','country_name' => 'Indonesia', 'phone_code'=>'62'];
        $rows[] = ['country_code' => 'IR','country_name' => 'Iran (Islamic Republic of)', 'phone_code'=>'98'];
        $rows[] = ['country_code' => 'IQ','country_name' => 'Iraq', 'phone_code'=>'964'];
        $rows[] = ['country_code' => 'IE','country_name' => 'Ireland', 'phone_code'=>'353'];
        $rows[] = ['country_code' => 'IL','country_name' => 'Israel', 'phone_code'=>'972'];
        $rows[] = ['country_code' => 'IT','country_name' => 'Italy', 'phone_code'=>'39'];
        $rows[] = ['country_code' => 'CI','country_name' => 'Ivory Coast', 'phone_code'=>'225'];
        $rows[] = ['country_code' => 'JE','country_name' => 'Jersey', 'phone_code'=>'+44-1534'];
        $rows[] = ['country_code' => 'JM','country_name' => 'Jamaica', 'phone_code'=>'+1-876'];
        $rows[] = ['country_code' => 'JP','country_name' => 'Japan', 'phone_code'=>'81'];
        $rows[] = ['country_code' => 'JO','country_name' => 'Jordan', 'phone_code'=>'962'];
        $rows[] = ['country_code' => 'KZ','country_name' => 'Kazakhstan', 'phone_code'=>'7'];
        $rows[] = ['country_code' => 'KE','country_name' => 'Kenya', 'phone_code'=>'254'];
        $rows[] = ['country_code' => 'KI','country_name' => 'Kiribati', 'phone_code'=>'686'];
        $rows[] = ['country_code' => 'KP','country_name' => 'Korea, Democratic People\'s Republic of', 'phone_code'=>'850'];
        $rows[] = ['country_code' => 'KR','country_name' => 'Korea, Republic of', 'phone_code'=>'82'];
        $rows[] = ['country_code' => 'XK','country_name' => 'Kosovo', 'phone_code'=>''];
        $rows[] = ['country_code' => 'KW','country_name' => 'Kuwait', 'phone_code'=>'965'];
        $rows[] = ['country_code' => 'KG','country_name' => 'Kyrgyzstan', 'phone_code'=>'996'];
        //$rows[] = ['country_code' => 'LA','country_name' => 'Lao People\'s Democratic Republic', 'phone_code'=>'856'];
        $rows[] = ['country_code' => 'LA','country_name' => 'Laos', 'phone_code'=>'856'];
        $rows[] = ['country_code' => 'LV','country_name' => 'Latvia', 'phone_code'=>'371'];
        $rows[] = ['country_code' => 'LB','country_name' => 'Lebanon', 'phone_code'=>'961'];
        $rows[] = ['country_code' => 'LS','country_name' => 'Lesotho', 'phone_code'=>'266'];
        $rows[] = ['country_code' => 'LR','country_name' => 'Liberia', 'phone_code'=>'231'];
        $rows[] = ['country_code' => 'LY','country_name' => 'Libyan Arab Jamahiriya', 'phone_code'=>'218'];
        $rows[] = ['country_code' => 'LI','country_name' => 'Liechtenstein', 'phone_code'=>'423'];
        $rows[] = ['country_code' => 'LT','country_name' => 'Lithuania', 'phone_code'=>'370'];
        $rows[] = ['country_code' => 'LU','country_name' => 'Luxembourg', 'phone_code'=>'352'];
        $rows[] = ['country_code' => 'MO','country_name' => 'Macau', 'phone_code'=>'853'];
        $rows[] = ['country_code' => 'MK','country_name' => 'Macedonia', 'phone_code'=>'389'];
        $rows[] = ['country_code' => 'MG','country_name' => 'Madagascar', 'phone_code'=>'261'];
        $rows[] = ['country_code' => 'MW','country_name' => 'Malawi', 'phone_code'=>'265'];
        $rows[] = ['country_code' => 'MY','country_name' => 'Malaysia', 'phone_code'=>'60'];
        $rows[] = ['country_code' => 'MV','country_name' => 'Maldives', 'phone_code'=>'960'];
        $rows[] = ['country_code' => 'ML','country_name' => 'Mali', 'phone_code'=>'223'];
        $rows[] = ['country_code' => 'MT','country_name' => 'Malta', 'phone_code'=>'356'];
        $rows[] = ['country_code' => 'MH','country_name' => 'Marshall Islands', 'phone_code'=>'692'];
        $rows[] = ['country_code' => 'MQ','country_name' => 'Martinique', 'phone_code'=>'596'];
        $rows[] = ['country_code' => 'MR','country_name' => 'Mauritania', 'phone_code'=>'222'];
        $rows[] = ['country_code' => 'MU','country_name' => 'Mauritius', 'phone_code'=>'230'];
        $rows[] = ['country_code' => 'TY','country_name' => 'Mayotte', 'phone_code'=>'269'];
        $rows[] = ['country_code' => 'MX','country_name' => 'Mexico', 'phone_code'=>'52'];
        $rows[] = ['country_code' => 'FM','country_name' => 'Micronesia, Federated States of', 'phone_code'=>'691'];
        $rows[] = ['country_code' => 'MD','country_name' => 'Moldova, Republic of', 'phone_code'=>'373'];
        $rows[] = ['country_code' => 'MC','country_name' => 'Monaco', 'phone_code'=>'377'];
        $rows[] = ['country_code' => 'MN','country_name' => 'Mongolia', 'phone_code'=>'976'];
        $rows[] = ['country_code' => 'ME','country_name' => 'Montenegro', 'phone_code'=>'381'];
        $rows[] = ['country_code' => 'MS','country_name' => 'Montserrat', 'phone_code'=>'+1-664'];
        $rows[] = ['country_code' => 'MA','country_name' => 'Morocco', 'phone_code'=>'212'];
        $rows[] = ['country_code' => 'MZ','country_name' => 'Mozambique', 'phone_code'=>'258'];
        $rows[] = ['country_code' => 'MM','country_name' => 'Myanmar', 'phone_code'=>'95'];
        $rows[] = ['country_code' => 'NA','country_name' => 'Namibia', 'phone_code'=>'264'];
        $rows[] = ['country_code' => 'NR','country_name' => 'Nauru', 'phone_code'=>'674'];
        $rows[] = ['country_code' => 'NP','country_name' => 'Nepal', 'phone_code'=>'977'];
        $rows[] = ['country_code' => 'NL','country_name' => 'Netherlands', 'phone_code'=>'31'];
        $rows[] = ['country_code' => 'AN','country_name' => 'Netherlands Antilles', 'phone_code'=>'599'];
        $rows[] = ['country_code' => 'NC','country_name' => 'New Caledonia', 'phone_code'=>'687'];
        $rows[] = ['country_code' => 'NZ','country_name' => 'New Zealand', 'phone_code'=>'64'];
        $rows[] = ['country_code' => 'NI','country_name' => 'Nicaragua', 'phone_code'=>'505'];
        $rows[] = ['country_code' => 'NE','country_name' => 'Niger', 'phone_code'=>'227'];
        $rows[] = ['country_code' => 'NG','country_name' => 'Nigeria', 'phone_code'=>'234'];
        $rows[] = ['country_code' => 'NU','country_name' => 'Niue', 'phone_code'=>'683'];
        $rows[] = ['country_code' => 'NF','country_name' => 'Norfolk Island', 'phone_code'=>'672'];
        $rows[] = ['country_code' => 'MP','country_name' => 'Northern Mariana Islands', 'phone_code'=>'+1-670'];
        $rows[] = ['country_code' => 'NO','country_name' => 'Norway', 'phone_code'=>'47'];
        $rows[] = ['country_code' => 'OM','country_name' => 'Oman', 'phone_code'=>'968'];
        $rows[] = ['country_code' => 'PK','country_name' => 'Pakistan', 'phone_code'=>'92'];
        $rows[] = ['country_code' => 'PW','country_name' => 'Palau', 'phone_code'=>'680'];
        $rows[] = ['country_code' => 'PS','country_name' => 'Palestinian Territory', 'phone_code'=>'970'];
        $rows[] = ['country_code' => 'PA','country_name' => 'Panama', 'phone_code'=>'507'];
        $rows[] = ['country_code' => 'PG','country_name' => 'Papua New Guinea', 'phone_code'=>'675'];
        $rows[] = ['country_code' => 'PY','country_name' => 'Paraguay', 'phone_code'=>'595'];
        $rows[] = ['country_code' => 'PE','country_name' => 'Peru', 'phone_code'=>'51'];
        $rows[] = ['country_code' => 'PH','country_name' => 'Philippines', 'phone_code'=>'63'];
        $rows[] = ['country_code' => 'PN','country_name' => 'Pitcairn', 'phone_code'=>''];
        $rows[] = ['country_code' => 'PL','country_name' => 'Poland', 'phone_code'=>'48'];
        $rows[] = ['country_code' => 'PT','country_name' => 'Portugal', 'phone_code'=>'351'];
        $rows[] = ['country_code' => 'PR','country_name' => 'Puerto Rico', 'phone_code'=>'+1-787 and 1-939'];
        $rows[] = ['country_code' => 'QA','country_name' => 'Qatar', 'phone_code'=>'974'];
        $rows[] = ['country_code' => 'RE','country_name' => 'Reunion', 'phone_code'=>'262'];
        $rows[] = ['country_code' => 'RO','country_name' => 'Romania', 'phone_code'=>'40'];
        $rows[] = ['country_code' => 'RU','country_name' => 'Russia', 'phone_code'=>'7'];
        $rows[] = ['country_code' => 'RW','country_name' => 'Rwanda', 'phone_code'=>'250'];
        $rows[] = ['country_code' => 'BL','country_name' => 'Saint Barthélemy', 'phone_code'=>'590'];
        $rows[] = ['country_code' => 'KN','country_name' => 'Saint Kitts and Nevis', 'phone_code'=>'+1-869'];
        $rows[] = ['country_code' => 'LC','country_name' => 'Saint Lucia', 'phone_code'=>'+1-758'];
        $rows[] = ['country_code' => 'MF','country_name' => 'Saint Martin', 'phone_code'=>'590'];
        $rows[] = ['country_code' => 'VC','country_name' => 'Saint Vincent and the Grenadines', 'phone_code'=>'+1-784'];
        $rows[] = ['country_code' => 'WS','country_name' => 'Samoa', 'phone_code'=>'685'];
        $rows[] = ['country_code' => 'SM','country_name' => 'San Marino', 'phone_code'=>'378'];
        $rows[] = ['country_code' => 'ST','country_name' => 'Sao Tome and Principe', 'phone_code'=>'239'];
        $rows[] = ['country_code' => 'SA','country_name' => 'Saudi Arabia', 'phone_code'=>'966'];
        $rows[] = ['country_code' => 'SN','country_name' => 'Senegal', 'phone_code'=>'221'];
        $rows[] = ['country_code' => 'RS','country_name' => 'Serbia', 'phone_code'=>'381'];
        $rows[] = ['country_code' => 'SC','country_name' => 'Seychelles', 'phone_code'=>'248'];
        $rows[] = ['country_code' => 'SL','country_name' => 'Sierra Leone', 'phone_code'=>'232'];
        $rows[] = ['country_code' => 'SG','country_name' => 'Singapore', 'phone_code'=>'65'];
        $rows[] = ['country_code' => 'SK','country_name' => 'Slovakia', 'phone_code'=>'421'];
        $rows[] = ['country_code' => 'SI','country_name' => 'Slovenia', 'phone_code'=>'386'];
        $rows[] = ['country_code' => 'SB','country_name' => 'Solomon Islands', 'phone_code'=>'677'];
        $rows[] = ['country_code' => 'SO','country_name' => 'Somalia', 'phone_code'=>'252'];
        $rows[] = ['country_code' => 'ZA','country_name' => 'South Africa', 'phone_code'=>'27'];
        $rows[] = ['country_code' => 'GS','country_name' => 'South Georgia and the South Sandwich Islands', 'phone_code'=>'0'];
        $rows[] = ['country_code' => 'ES','country_name' => 'Spain', 'phone_code'=>'34'];
        $rows[] = ['country_code' => 'LK','country_name' => 'Sri Lanka', 'phone_code'=>'94'];
        $rows[] = ['country_code' => 'SH','country_name' => 'St. Helena', 'phone_code'=>'290'];
        $rows[] = ['country_code' => 'PM','country_name' => 'St. Pierre and Miquelon', 'phone_code'=>'508'];
        $rows[] = ['country_code' => 'SD','country_name' => 'Sudan', 'phone_code'=>'249'];
        $rows[] = ['country_code' => 'SR','country_name' => 'Suriname', 'phone_code'=>'597'];
        $rows[] = ['country_code' => 'SJ','country_name' => 'Svalbard and Jan Mayen Islands', 'phone_code'=>'47'];
        $rows[] = ['country_code' => 'SZ','country_name' => 'Swaziland', 'phone_code'=>'268'];
        $rows[] = ['country_code' => 'SE','country_name' => 'Sweden', 'phone_code'=>'46'];
        $rows[] = ['country_code' => 'CH','country_name' => 'Switzerland', 'phone_code'=>'41'];
        $rows[] = ['country_code' => 'SY','country_name' => 'Syrian Arab Republic', 'phone_code'=>'963'];
        $rows[] = ['country_code' => 'TW','country_name' => 'Taiwan', 'phone_code'=>'886'];
        $rows[] = ['country_code' => 'TJ','country_name' => 'Tajikistan', 'phone_code'=>'992'];
        $rows[] = ['country_code' => 'TZ','country_name' => 'Tanzania, United Republic of', 'phone_code'=>'255'];
        $rows[] = ['country_code' => 'TH','country_name' => 'Thailand', 'phone_code'=>'66'];
        $rows[] = ['country_code' => 'TG','country_name' => 'Togo', 'phone_code'=>'228'];
        $rows[] = ['country_code' => 'TK','country_name' => 'Tokelau', 'phone_code'=>'690'];
        $rows[] = ['country_code' => 'TO','country_name' => 'Tonga', 'phone_code'=>'676'];
        $rows[] = ['country_code' => 'TT','country_name' => 'Trinidad and Tobago', 'phone_code'=>'+1-868'];
        $rows[] = ['country_code' => 'TN','country_name' => 'Tunisia', 'phone_code'=>'216'];
        $rows[] = ['country_code' => 'TR','country_name' => 'Turkey', 'phone_code'=>'90'];
        $rows[] = ['country_code' => 'TM','country_name' => 'Turkmenistan', 'phone_code'=>'993'];
        $rows[] = ['country_code' => 'TC','country_name' => 'Turks and Caicos Islands', 'phone_code'=>'+1-649'];
        $rows[] = ['country_code' => 'TV','country_name' => 'Tuvalu', 'phone_code'=>'688'];
        $rows[] = ['country_code' => 'UG','country_name' => 'Uganda', 'phone_code'=>'256'];
        $rows[] = ['country_code' => 'UA','country_name' => 'Ukraine', 'phone_code'=>'380'];
        $rows[] = ['country_code' => 'AE','country_name' => 'United Arab Emirates', 'phone_code'=>'971'];
        $rows[] = ['country_code' => 'GB','country_name' => 'United Kingdom', 'phone_code'=>'44'];
        $rows[] = ['country_code' => 'US','country_name' => 'United States', 'phone_code'=>'1'];
        $rows[] = ['country_code' => 'UM','country_name' => 'United States minor outlying islands', 'phone_code'=>''];
        $rows[] = ['country_code' => 'UY','country_name' => 'Uruguay', 'phone_code'=>'598'];
        $rows[] = ['country_code' => 'UZ','country_name' => 'Uzbekistan', 'phone_code'=>'998'];
        $rows[] = ['country_code' => 'VU','country_name' => 'Vanuatu', 'phone_code'=>'678'];
        $rows[] = ['country_code' => 'VA','country_name' => 'Vatican City State', 'phone_code'=>'379'];
        $rows[] = ['country_code' => 'VE','country_name' => 'Venezuela', 'phone_code'=>'58'];
        $rows[] = ['country_code' => 'VN','country_name' => 'Vietnam', 'phone_code'=>'84'];
        $rows[] = ['country_code' => 'VG','country_name' => 'Virgin Islands (British)', 'phone_code'=>'+1-284'];
        $rows[] = ['country_code' => 'VI','country_name' => 'Virgin Islands (U.S.)', 'phone_code'=>'+1-340'];
        $rows[] = ['country_code' => 'WF','country_name' => 'Wallis and Futuna Islands', 'phone_code'=>'681'];
        $rows[] = ['country_code' => 'EH','country_name' => 'Western Sahara', 'phone_code'=>'212'];
        $rows[] = ['country_code' => 'YE','country_name' => 'Yemen', 'phone_code'=>'967'];
        $rows[] = ['country_code' => 'YU','country_name' => 'Yugoslavia', 'phone_code'=>''];
        $rows[] = ['country_code' => 'ZR','country_name' => 'Zaire', 'phone_code'=>''];
        $rows[] = ['country_code' => 'ZM','country_name' => 'Zambia', 'phone_code'=>'260'];
        $rows[] = ['country_code' => 'ZW','country_name' => 'Zimbabwe', 'phone_code'=>'263'];
        DB::table('countries')->insert($rows);



    }
}
